Usar tipos enumeradores
ufla-ppoo/trabalho-adventure pull request #4
Opened 2023-02-26 19:23 UTC by Nxxxlxs

Conversão das palavras de comando do jogo do tipo `String` para o tipo `Enum` seguindo o padrão proposto pelo livro _Programação Orientada a Objetos com Java_ de Barnes e Kolling. 

Notas: 
1. Foi criada a mesma estrutura de `HashMap<String, ComandoEnum>` e tipo de comparação no método `processarComando()`  da classe `Jogo`, de acordo com os exemplos do livro.
2. Não foi possível encontrar no livro uma proposta para alteração das palavras de __direção__, e na tentativa foi identificado que o código não executa uma verificação de validade da segunda palavra o que poderia exigir modificações adicionais (isso foi notado ao tentar replicar a mudança nas palavras de comando, nas palavras de direção). Com isso, as direções não foram alteradas pelo motivo de não conseguir mensurar o impacto delas no código tendo em vista que é utilizado para ensino em uma disciplina.

Qualquer alteração necessária, e até mesmo a aprovação para alteração nas __direções__ é só avisar.

Resolve: #2

2023-02-27 12:26 UTC, caburu requested changes
Olá pessoal, obrigado pelas boas contribuições. Seguem alguns comentários para torná-las ainda melhor.

Reparem que, com a existência de um enum para as palavras de comando, nós podemos repensar o código para deixá-lo com um melhor design. 

1. Vejam as observações abaixo no código sobre o enum criado.
2.  Vejam que a classe `Comando` tem um atributo chamado `palavraDeComando` do tipo String. Mas com a existência do enum `PalavraDeComando`, ele deveria ser agora desse tipo.
  - É necessário alterar o construtor para receber uma `PalavraDeComando`, o método `getPalavraDeComando` e o método `ehDesconhecido` (que agora deve verificar se a palavra de comando é `DESCONHECIDA`).
3. Na classe `PalavrasComando`, além das observações no código abaixo, seria interessante criar um método com a seguinte assinatura `public PalavraDeComando obterPalavraDeComando(String palavraDeComando)` que buscasse a string no HashMap de comandos válidos e retornasse `DESCONHECIDA` se não encontrasse.
4. O método `pegarComando` da classe `Analisador` precisaria ser alterado para criar um objeto comando passando o enum `PalavraDeComando` obtido com o método do item anterior (não seria mais necessário ter um if/else para isso).
5. Tratar os comentários no código da classe `Jogo` abaixo.
6. Uma **observação adicional importante**: como aceitei um Pull Request de outra alteração, o código de vocês está em conflito com a versão atual do repositório. Talvez a maneira mais fácil de resolver seria refazer o processo a partir da versão mais atual do código.

Qualquer dúvida, estou à disposição. Mais uma vez, obrigado.

2023-02-27 12:26 UTC, caburu commented on src/br/ufla/gac106/s2022_1/seuJogo/ComandoEnum.java
> +public enum ComandoEnum {
No livro o nome usado é `CommandWord` que poderia ser traduzido para `PalavraDeComando`. Seria interessante usar este termo, pois fica mais claro para os estudantes.
- Além de ser interessante evitar o sufixo `Enum` ao nomear um enum, por ser redundante.

2023-02-27 12:26 UTC, caburu commented on src/br/ufla/gac106/s2022_1/seuJogo/ComandoEnum.java
> +  private String comandoEnum;
Seguindo a mesma ideia, o atributo poderia se chamar `palavraDeComando`.

2023-02-27 12:26 UTC, caburu commented on src/br/ufla/gac106/s2022_1/seuJogo/ComandoEnum.java
> +  AJUDA("ajuda");
O livro acrescenta a palavra de comando `DESCONHECIDA("?")`. Seria interessante acrescentar aqui também.

Obs.: Para manter o estilo de codificação, peço que utilizem 4 espaços como tabulação no arquivo acrescentado.

2023-02-27 12:26 UTC, caburu commented on src/br/ufla/gac106/s2022_1/seuJogo/PalavrasComando.java
> +  }
- Faltou o modificador `public`.
- Lembrem-se que, ao acrescentar a opção `DESCONHECIDA`, será necessário incluir um `if` aqui para não acrescentá-la na coleção de comandos válidos.

2023-02-27 12:26 UTC, caburu commented on src/br/ufla/gac106/s2022_1/seuJogo/PalavrasComando.java
> +    return false;
Sugestão: o código ficaria mais simples se retornasse o resultado diretamente, em uma única linha:
`return comandosValidos.containsKey(umaString)`

2023-02-27 12:26 UTC, caburu commented on src/br/ufla/gac106/s2022_1/seuJogo/Jogo.java
> +        if (palavraDeComando == ComandoEnum.AJUDA) {
Com as alterações listadas acima, a palavra de comando poderia ser obtida utilizando: `PalavraDeComando palavraDeComando = comando.getPalavraDeComando();`
- Seria interessante também acrescentar um `if` para verificar se a palavra de comando é `DESCONHECIDA` e, nesse caso, informar o usuário algo como `"Não entendi o seu comando..."`.

2023-02-27 12:47 UTC, caburu commented on src/br/ufla/gac106/s2022_1/seuJogo/Jogo.java
> +        printarLocalizacao();
Uma observação adicional, o código original tem uma replicação de código que vocês identificaram e trataram criando o método `printarLocalizacao`. Mas essa replicação era proposital e é uma das alterações que se espera que os alunos façam ao implementar o trabalho.

2023-02-27 19:21 UTC, caburu reviewed
Olá @Nxxxlxs, muito obrigado pelo complemento das alterações! Elas ficaram ótimas.

Ficou faltando tratar apenas a questão do método `printarLocalizacao` (comentário acima). Seria possível tratá-la? Obrigado!

2023-02-27 19:40 UTC, Nxxxlxs commented
@caburu peço desculpas na demora pelo retorno, poderia verificar novamente ? Qualquer alteração necessária é só solicitar !

2023-02-28 11:38 UTC, caburu approved these changes
Imagina, sem pressa. As alterações ficaram muito boas!

Muito obrigado pelas contribuições.

2023-02-28 11:41 UTC, merged